"""
Bit semantics for ``trait_mask`` (BIGINT) on graph nodes.

Canonical documentation: ``docs/database/SPEC/features/`` (trait class / mask).
"""
from __future__ import annotations
CONCEPTUAL = 1 << 0
FACTUAL = 1 << 1
SPATIAL = 1 << 2
PERCEPTUAL = 1 << 3
TEMPORAL = 1 << 4
CONTROLLABLE = 1 << 5
EVENT_BASED = 1 << 6
MOBILE = 1 << 7
AUTO = 1 << 8
LOAD_BEARING = 1 << 9
TASK_MARKER = 1 << 10
SPATIAL_LOAD_BEARING = SPATIAL | LOAD_BEARING
DEVICE_TYPICAL_IOT_END = FACTUAL | PERCEPTUAL | TEMPORAL | CONTROLLABLE
ACCESS_TERMINAL = DEVICE_TYPICAL_IOT_END | SPATIAL | EVENT_BASED
WORLD_OBJECT_BASE = PERCEPTUAL | LOAD_BEARING
NPC_AGENT = FACTUAL | TEMPORAL | CONTROLLABLE | EVENT_BASED | MOBILE | AUTO
LOGICAL_ZONE = CONCEPTUAL | EVENT_BASED
WORLD_ENTRANCE = CONCEPTUAL | SPATIAL | CONTROLLABLE | EVENT_BASED
LOCATION_RELATIONSHIP_EDGE = CONCEPTUAL | SPATIAL
TASK = CONCEPTUAL | EVENT_BASED | TASK_MARKER
MASK_QUERY_ZERO_DESCRIPTION = 'trait_mask 过滤：0 表示不按位过滤（全量）。非 0 时使用按位与匹配；各位含义见数据库 SPEC 与本模块常量说明。'
