/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentsActivity: typeof import('./src/components/works/AgentsActivity.vue')['default']
    BootSequence: typeof import('./src/components/auth/BootSequence.vue')['default']
    ChatInput: typeof import('./src/components/works/ChatInput.vue')['default']
    CyberButton: typeof import('./src/components/auth/CyberButton.vue')['default']
    CyberInput: typeof import('./src/components/auth/CyberInput.vue')['default']
    Dashboard: typeof import('./src/components/works/Dashboard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElResult: typeof import('element-plus/es')['ElResult']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    GlitchText: typeof import('./src/components/auth/GlitchText.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    ParticleBackground: typeof import('./src/components/auth/ParticleBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanlineOverlay: typeof import('./src/components/auth/ScanlineOverlay.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SystemStatus: typeof import('./src/components/auth/SystemStatus.vue')['default']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    TodoList: typeof import('./src/components/works/TodoList.vue')['default']
  }
}
